// flow-typed signature: 028fc532c7362ce2a01cd90b4efe0515
// flow-typed version: <<STUB>>/react-loading_v2.0.2/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loading/dist/react-loading' {
  declare module.exports: any;
}

declare module 'react-loading/jest.setup' {
  declare module.exports: any;
}

declare module 'react-loading/lib/__tests__/react-loading.spec' {
  declare module.exports: any;
}

declare module 'react-loading/lib/react-loading' {
  declare module.exports: any;
}

declare module 'react-loading/lib/svg/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loading/dist/react-loading.js' {
  declare module.exports: $Exports<'react-loading/dist/react-loading'>;
}
declare module 'react-loading/jest.setup.js' {
  declare module.exports: $Exports<'react-loading/jest.setup'>;
}
declare module 'react-loading/lib/__tests__/react-loading.spec.jsx' {
  declare module.exports: $Exports<'react-loading/lib/__tests__/react-loading.spec'>;
}
declare module 'react-loading/lib/react-loading.jsx' {
  declare module.exports: $Exports<'react-loading/lib/react-loading'>;
}
declare module 'react-loading/lib/svg/index.js' {
  declare module.exports: $Exports<'react-loading/lib/svg/index'>;
}
