/* @flow */

export const FETCH_MOVIES_START: string = 'FETCH_MOVIES_START'
export const FETCH_MOVIES_SUCCESS: string = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAIL: string = 'FETCH_MOVIES_FAIL'
export const FETCH_SINGLE_MOVIE_START: string = 'FETCH_SINGLE_MOVIE_START'
export const FETCH_SINGLE_MOVIE_SUCCESS: string = 'FETCH_SINGLE_MOVIE_SUCCESS'
export const FETCH_SINGLE_MOVIE_FAIL: string = 'FETCH_SINGLE_MOVIE_FAIL'
export const SORT_MOVIES_BY_RELEASE_DATE: string = 'SORT_MOVIES_BY_RELEASE_DATE'
export const SORT_MOVIES_BY_RATING: string = 'SORT_MOVIES_BY_RATING'
export const SEARCH_MOVIES_BY_TITLE: string = 'SEARCH_MOVIES_BY_TITLE'
export const SEARCH_MOVIES_BY_GENRE: string = 'SEARCH_MOVIES_BY_GENRE'
